server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdemo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    cluster:
      nodes:
        - 47.106.149.90:6380
        - 47.106.149.90:6381
        - 47.106.149.90:6382
        - 47.106.149.90:6383
        - 47.106.149.90:6384
        - 47.106.149.90:6385
  rabbitmq:
    host: 47.106.149.90
    port: 5672
    username: fateravel
    password: 123456
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info