server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8799/springbootdemo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: localhost
    port: 6379
    cluster:
      nodes:
        - localhost:6380
        - localhost:6381
        - localhost:6382
        - localhost:6383
        - localhost:6384
        - localhost:6385
  rabbitmq:
    host: localhost
    port: 5672
    username: fateravel
    password: 123456
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: debug