server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdemo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
#    cluster:
#      nodes: 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 47.106.149.90
    port: 5672
    username: fateravel
    password: 123456
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info